package sic.autenticarda.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-14T14:43:05.522-05:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://ws.autenticarda.sic/", name = "AutenticarDA")
@XmlSeeAlso({ObjectFactory.class})
public interface AutenticarDA {

    @WebMethod
    @RequestWrapper(localName = "autenticarDA", targetNamespace = "http://ws.autenticarda.sic/", className = "sic.autenticarda.ws.AutenticarDA_Type")
    @ResponseWrapper(localName = "autenticarDAResponse", targetNamespace = "http://ws.autenticarda.sic/", className = "sic.autenticarda.ws.AutenticarDAResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String autenticarDA(

        @WebParam(name = "trama", targetNamespace = "")
        java.lang.String trama
    );
}
