package sic.autenticarda.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-14T14:43:05.597-05:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "AutenticarDAService",
                  wsdlLocation = "http://servicios.sic.gov.co/AutenticarDA/AutenticarDA?wsdl",
                  targetNamespace = "http://ws.autenticarda.sic/")
public class AutenticarDAService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.autenticarda.sic/", "AutenticarDAService");
    public final static QName AutenticarDAPort = new QName("http://ws.autenticarda.sic/", "AutenticarDAPort");
    static {
        URL url = null;
        try {
            url = new URL("http://servicios.sic.gov.co/AutenticarDA/AutenticarDA?wsdl");
        } catch (MalformedURLException e) {
        	e.printStackTrace();
            java.util.logging.Logger.getLogger(AutenticarDAService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://servicios.sic.gov.co/AutenticarDA/AutenticarDA?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutenticarDAService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutenticarDAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutenticarDAService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AutenticarDAService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AutenticarDAService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AutenticarDAService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AutenticarDA
     */
    @WebEndpoint(name = "AutenticarDAPort")
    public AutenticarDA getAutenticarDAPort() {
        return super.getPort(AutenticarDAPort, AutenticarDA.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutenticarDA
     */
    @WebEndpoint(name = "AutenticarDAPort")
    public AutenticarDA getAutenticarDAPort(WebServiceFeature... features) {
        return super.getPort(AutenticarDAPort, AutenticarDA.class, features);
    }

}
